# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modifyDate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('label', models.CharField(max_length=20, verbose_name='标签')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
